[1,"Error occurred during cleanup: Error: El proceso no tiene acceso al archivo porque est√° siendo utilizado por otro proceso. (os error 32): remove 'C:\\Users\\chaca\\AppData\\Local\\Temp\\quarto-sessiona3eb511efe084ad9'\n"]
